# Generated by Django 4.2.2 on 2023-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('foto', models.ImageField(default=None, null=True, upload_to='pratos/', verbose_name='Imagem_do_prato')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('disponivel', models.BooleanField(default=False, verbose_name='Disponível')),
                ('categoria', models.CharField(choices=[('entradas', 'Entradas'), ('pratos_principais', 'Pratos Principais'), ('massas_risotos', 'Massas e Risotos'), ('sanduiches_hamburgueres', 'Sanduíches e Hambúrgueres'), ('sobremesas', 'Sobremesas'), ('bebidas', 'Bebidas'), ('especiais_chef', 'Especiais do Chef')], max_length=30, verbose_name='Categoria')),
                ('foto', models.ImageField(default=None, null=True, upload_to='pratos/', verbose_name='Imagem_do_prato')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preco')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('adicional', models.ManyToManyField(related_name='adicionais', to='pratos.adicional')),
            ],
        ),
    ]
