# Generated by Django 4.2.2 on 2023-07-01 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('foto', models.ImageField(default=None, null=True, upload_to='pratos/', verbose_name='Imagem_do_prato')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='comentário')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('respostas', models.ManyToManyField(blank=True, to='pratos.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('disponivel', models.BooleanField(default=False, verbose_name='Disponível')),
                ('categoria', models.CharField(choices=[('entradas', 'Entradas'), ('pratos_principais', 'Pratos Principais'), ('massas_risotos', 'Massas e Risotos'), ('sanduiches_hamburgueres', 'Sanduíches e Hambúrgueres'), ('sobremesas', 'Sobremesas'), ('bebidas', 'Bebidas'), ('especiais_chef', 'Especiais do Chef')], max_length=30, verbose_name='Categoria')),
                ('foto', models.ImageField(default=None, null=True, upload_to='pratos/', verbose_name='Imagem_do_prato')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preco')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('adicional', models.ManyToManyField(related_name='adicionais', to='pratos.adicional')),
                ('comentarios', models.ManyToManyField(default=None, related_name='comentarios', to='pratos.comentario')),
            ],
        ),
    ]
