# Generated by Django 4.2.2 on 2023-06-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='respostas',
        ),
        migrations.AlterField(
            model_name='prato',
            name='comentarios',
            field=models.ManyToManyField(default=None, related_name='comentarios', to='pratos.comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='respostas',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pratos.comentario'),
        ),
    ]
