# Generated by Django 4.2 on 2023-07-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('quantidade_estoque', models.PositiveIntegerField(verbose_name='Quantidade_Estoque')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preco')),
            ],
        ),
        migrations.AddField(
            model_name='prato',
            name='ingredientes',
            field=models.ManyToManyField(related_name='ingredientes', to='pratos.ingrediente'),
        ),
    ]
