# Generated by Django 4.2.2 on 2023-06-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='avaliacao',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='pratos.comentario'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='comentarios',
            field=models.ManyToManyField(default=None, related_name='comentarios', to='pratos.comentario'),
        ),
    ]
