# Generated by Django 4.2 on 2023-07-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0002_ingrediente_prato_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='preco',
        ),
    ]
