# Generated by Django 4.2.2 on 2023-06-27 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0002_alter_comentario_likes_remove_comentario_respostas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='respostas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pratos.comentario'),
        ),
    ]
