# Generated by Django 4.2 on 2023-07-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0003_remove_ingrediente_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(default=None, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
