# Generated by Django 4.2.2 on 2023-06-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0003_alter_comentario_respostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='respostas',
        ),
        migrations.AddField(
            model_name='comentario',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='pratos.comentario'),
        ),
    ]
