# Generated by Django 4.2.2 on 2023-06-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0004_remove_comentario_respostas_comentario_respostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='avaliacao',
        ),
    ]
