# Generated by Django 4.2 on 2023-07-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0005_ingrediente_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='QuantidadeUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.ingrediente')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.prato')),
            ],
        ),
    ]
