# Generated by Django 4.2 on 2023-07-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0006_ingrediente_quantidade_utilizada_quantidadeutilizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='quantidade_utilizada',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidade',
        ),
        migrations.DeleteModel(
            name='QuantidadeUtilizada',
        ),
    ]
