# Generated by Django 4.2 on 2023-07-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0007_remove_ingrediente_quantidade_utilizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidade_medida',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ManyToManyField(through='pratos.IngredienteReceita', to='pratos.ingrediente')),
                ('prato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pratos.prato')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientereceita',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.ingrediente'),
        ),
        migrations.AddField(
            model_name='ingredientereceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.receita'),
        ),
    ]
