# Generated by Django 4.2 on 2023-07-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0008_ingredientereceita_ingrediente_unidade_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientereceita',
            name='unidade_medida',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
    ]
