# Generated by Django 4.2 on 2023-07-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0009_remove_ingredientereceita_unidade_medida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredientes_disponiveis',
            field=models.BooleanField(default=False, verbose_name='ingredientes_disponiveis'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='prato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pratos.prato'),
        ),
    ]
