# Generated by Django 4.2.2 on 2023-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0010_receita_ingredientes_disponiveis_alter_receita_prato'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='nome',
            field=models.CharField(default='Receita', max_length=50),
            preserve_default=False,
        ),
    ]
