# Generated by Django 5.0.7 on 2025-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0012_remove_prato_ingredientes_alter_adicional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('pratos_principais', 'Pratos Principais'), ('massas_risotos', 'Massas e Risotos'), ('sanduiches_hamburgueres', 'Lanches'), ('sobremesas', 'Sobremesas'), ('bebidas', 'Bebidas'), ('especiais_chef', 'Especiais do Chef'), ('frutos_do_mar', 'Frutos do mar'), ('vegetariano', 'Vegetariano')], max_length=30, verbose_name='Categoria'),
        ),
    ]
