# Generated by Django 5.0.7 on 2025-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0013_alter_prato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='recomendado',
            field=models.BooleanField(default=False, verbose_name='Recomendado'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
    ]
