# Generated by Django 5.0.7 on 2025-08-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0014_prato_recomendado_alter_prato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
    ]
