# Generated by Django 4.2 on 2023-07-03 18:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero da mesa')),
                ('status', models.CharField(default='disponível', max_length=20, verbose_name='Status da mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preco total do pedido')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('local_retirada', models.CharField(choices=[('restaurante', 'Retirar no Restaurante'), ('entrega', 'Entrega em Casa')], max_length=20, null=True, verbose_name='Local de Retirada')),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão de Crédito'), ('transferencia', 'Transferência Bancária')], max_length=20, null=True, verbose_name='Método de Pagamento')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.endereco')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('horario', models.TimeField(null=True)),
                ('observacao', models.TextField(blank=True, default=None, verbose_name='Observações')),
                ('qnt_pessoas', models.IntegerField(default='1')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preco total da resarva')),
                ('status', models.CharField(default='Pendente', max_length=20, verbose_name='status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ManyToManyField(to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='No Carrinho', max_length=50)),
                ('observacao', models.TextField(blank=True, default=None, verbose_name='Observações')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('adicional', models.ManyToManyField(blank=True, to='pratos.adicional')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pratos', to='pedidos.pedido')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.prato')),
            ],
        ),
    ]
