# Generated by Django 4.2.2 on 2023-06-25 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Num_mesa')),
                ('status', models.CharField(max_length=20, verbose_name='Status_mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observações')),
                ('data_pedido', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco_total')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('local_retirada', models.CharField(choices=[('restaurante', 'Retirar no Restaurante'), ('reserva', 'Fazer Reserva'), ('entrega', 'Entrega em Casa')], max_length=20, verbose_name='Local de Retirada')),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão de Crédito'), ('transferencia', 'Transferência Bancária')], max_length=20, verbose_name='Método de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('adicional', models.ManyToManyField(blank=True, to='pratos.adicional')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pratos', to='pedidos.pedido')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.prato')),
            ],
        ),
    ]
