# Generated by Django 4.2.2 on 2023-07-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='local_retirada',
            field=models.CharField(choices=[('restaurante', 'Retirar no Restaurante'), ('entrega', 'Entrega em Casa')], max_length=20, null=True, verbose_name='Local de Retirada'),
        ),
    ]
