# Generated by Django 4.2.2 on 2023-06-30 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_alter_cliente_options_alter_cliente_managers_and_more'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.endereco'),
        ),
        migrations.AddField(
            model_name='pedidoprato',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoprato',
            name='nome_cliente',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidoprato',
            name='status',
            field=models.CharField(default='No Carrinho', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacao',
            field=models.TextField(blank=True, default=None, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='local_retirada',
            field=models.CharField(choices=[('restaurante', 'Retirar no Restaurante'), ('entrega', 'Entrega em Casa')], max_length=20, verbose_name='Local de Retirada'),
        ),
        migrations.AlterField(
            model_name='pedidoprato',
            name='pedido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pratos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(null=True),
        ),
    ]
