# Generated by Django 4.2.2 on 2023-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprato',
            name='id_pagamento',
            field=models.CharField(default='123123', max_length=100),
        ),
    ]
