# Generated by Django 4.2.2 on 2023-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacao',
            field=models.TextField(blank=True, default=None, verbose_name='Observações'),
        ),
    ]
