# Generated by Django 4.2.2 on 2023-06-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_reserva_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pedido',
        ),
    ]
