# Generated by Django 4.2.2 on 2023-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidoprato_id_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoprato',
            name='id_pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pagamento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
