# Generated by Django 5.0.7 on 2025-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedidoprato_id_pagamento_pedido_id_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('indisponível', 'Indisponível')], default='Disponível', max_length=20, verbose_name='Status da mesa'),
        ),
    ]
