# Generated by Django 4.2.2 on 2023-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(default=None, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
