# Generated by Django 4.2.2 on 2023-06-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_tipo_conta'),
        ('pedidos', '0006_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprato',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pedidoprato',
            name='status',
            field=models.CharField(default='No Carrinho', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(verbose_name='Endereçao'),
        ),
    ]
