# Generated by Django 4.2.2 on 2023-06-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(null=True),
        ),
    ]
