# Generated by Django 4.2.2 on 2023-06-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_reserva_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprato',
            name='nome_cliente',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
