# Generated by Django 5.0.7 on 2025-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='21:00')),
                ('reservation_deadline', models.PositiveIntegerField(default=9)),
                ('time_jump', models.PositiveIntegerField(default=1)),
                ('delivery_fee', models.FloatField(default=8.0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='PointSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.PositiveIntegerField(default=20)),
                ('indicated', models.PositiveIntegerField(default=10)),
                ('per_purchase_value', models.PositiveIntegerField(default=10)),
                ('per_rs', models.PositiveIntegerField(default=1)),
                ('rs_value', models.FloatField(default=0.2)),
            ],
        ),
    ]
