# Generated by Django 4.2.2 on 2023-06-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_afiliado',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
