# Generated by Django 4.2.2 on 2023-06-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_afiliado',
            field=models.CharField(max_length=255),
        ),
    ]
