# Generated by Django 4.2.2 on 2023-06-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_codigo_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontos de afiliado'),
        ),
    ]
