# Generated by Django 4.2.2 on 2023-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_remove_cliente_endereco_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='ponto_referencia',
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado_cidade',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='nome',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='telefone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
