# Generated by Django 4.2.2 on 2023-06-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_endereco_cidade_remove_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
